#pragma once

#include <windows.h>

#include <string>
#include <vector>

namespace cpulytics {

// The tray icon, a base64 .ico with 16/24/32 px images, so the binary needs no
// resource file and no external asset.
inline const char* icon_base64() {
    static const char* kIcon =
    "AAABAAMAEBAAAAEAIABoBAAANgAAABgYAAABACAAiAkAAJ4EAAAgIAAAAQAgAKgQAAAmDgAAKAAAABAAAAAgAAAAAQAgAAAAAAAA"
    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAxLCav8SwmmAAAAAAxLCaj8Swmo8AAAAAxLCaYMSwmr8AAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAr7g/QMSwmv+9snu/r7g/gMGxjd/BsY3fr7g/gL2ye7/EsJr/r7g/QAAAAAAAAAAAAAAAAAAAAAAAAAAAr7g/QIOE"
    "NP9eTkD/W080/1hQKf9cTzr/XE86/1hQKf9bTzT/Xk5A/4OENP+vuD9AAAAAAAAAAAAAAAAAxLCav8Swmv9eTkD/Sj8l/3VzMP88"
    "LiL/RmZx/0Zmcf88LiL/S0yQ/z81Pf9eTkD/xLCa/8Swmr8AAAAAAAAAAMSwmmC9snu/W080/1hQKf+vuD//PC4i/1Gfwf9Rn8H/"
    "PC4i/1tr//9DPVn/W080/72ye7/EsJpgAAAAAAAAAAAAAAAAr7g/gFhQKf9YUCn/r7g//zwuIv9Rn8H/UZ/B/zwuIv9ba///Qz1Z"
    "/1hQKf+vuD+AAAAAAAAAAAAAAAAAxLCaj8Gxjd9cTzr/WFAp/6+4P/88LiL/UZ/B/1Gfwf88LiL/W2v//0M9Wf9cTzr/wbGN38Sw"
    "mo8AAAAAAAAAAMSwmo/BsY3fXE86/1hQKf+vuD//PC4i/1Gfwf9Rn8H/PC4i/1tr//9DPVn/XE86/8Gxjd/EsJqPAAAAAAAAAAAA"
    "AAAAr7g/gFhQKf9YUCn/r7g//zwuIv9Rn8H/UZ/B/zwuIv9ba///Qz1Z/1hQKf+vuD+AAAAAAAAAAAAAAAAAxLCaYL2ye79bTzT/"
    "PC4i/zwuIv88LiL/UZ/B/1Gfwf88LiL/W2v//0M9Wf9bTzT/vbJ7v8SwmmAAAAAAAAAAAMSwmr/EsJr/Xk5A/zwuIv88LiL/PC4i"
    "/1Gfwf9Rn8H/PC4i/1tr//9DPVn/Xk5A/8Swmv/EsJq/AAAAAAAAAAAAAAAAr7g/QIOENP9eTkD/W080/1hQKf9nh4r/Z4eK/1hQ"
    "Kf9yfdr/Y1lp/4OENP+vuD9AAAAAAAAAAAAAAAAAAAAAAAAAAACvuD9AxLCa/72ye7+vuD+AwbGN38Gxjd+vuD+AvbJ7v8Swmv+v"
    "uD9AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMSwmr/EsJpgAAAAAMSwmo/EsJqPAAAAAMSwmmDEsJq/AAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAAAABgAAAAwAAAAAQAgAAAA"
    "AAAACQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAMSwmv/EsJr/xLCaQAAAAAAAAAAAxLCa/8Swmv8AAAAAAAAAAMSwmkDEsJr/xLCa/wAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAr7g/EMSwmv/EsJr/u7NzcK+4P0CvuD9AxLCa/8Swmv+vuD9Ar7g/QLuzc3DE"
    "sJr/xLCa/6+4PxAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACvuD9gr7g//6KPfP+ij3z/lpRI/5KVN/+SlTf/"
    "oo98/6KPfP+SlTf/kpU3/5aUSP+ij3z/oo98/6+4P/+vuD9gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAK+4PxCvuD//UUcn"
    "/zwuIv88LiL/PC4i/zwuIv88LiL/PC4i/zwuIv88LiL/PC4i/zwuIv88LiL/PC4i/1FHJ/+vuD//r7g/EAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAxLCa/8Swmv+ij3z/PC4i/zwuIv9YUCn/WFAp/zwuIv88LiL/Q1NX/0NTV/88LiL/PC4i/0M9Wf9DPVn/PC4i/zwuIv+i"
    "j3z/xLCa/8Swmv8AAAAAAAAAAAAAAAAAAAAAxLCa/8Swmv+ij3z/PC4i/zwuIv+vuD//r7g//zwuIv88LiL/WcX3/1nF9/88LiL/"
    "PC4i/1tr//9ba///PC4i/zwuIv+ij3z/xLCa/8Swmv8AAAAAAAAAAAAAAAAAAAAAxLCaQLuzc3CWlEj/PC4i/zwuIv+vuD//r7g/"
    "/zwuIv88LiL/WcX3/1nF9/88LiL/PC4i/1tr//9ba///PC4i/zwuIv+WlEj/u7NzcMSwmkAAAAAAAAAAAAAAAAAAAAAAAAAAAK+4"
    "P0CSlTf/PC4i/zwuIv+vuD//r7g//zwuIv88LiL/WcX3/1nF9/88LiL/PC4i/1tr//9ba///PC4i/zwuIv+SlTf/r7g/QAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAK+4P0CSlTf/PC4i/zwuIv+vuD//r7g//zwuIv88LiL/WcX3/1nF9/88LiL/PC4i/1tr//9ba///"
    "PC4i/zwuIv+SlTf/r7g/QAAAAAAAAAAAAAAAAAAAAAAAAAAAxLCa/8Swmv+ij3z/PC4i/zwuIv+vuD//r7g//zwuIv88LiL/WcX3"
    "/1nF9/88LiL/PC4i/1tr//9ba///PC4i/zwuIv+ij3z/xLCa/8Swmv8AAAAAAAAAAAAAAAAAAAAAxLCa/8Swmv+ij3z/PC4i/zwu"
    "Iv+vuD//r7g//zwuIv88LiL/WcX3/1nF9/88LiL/PC4i/1tr//9ba///PC4i/zwuIv+ij3z/xLCa/8Swmv8AAAAAAAAAAAAAAAAA"
    "AAAAAAAAAK+4P0CSlTf/PC4i/zwuIv+vuD//r7g//zwuIv88LiL/WcX3/1nF9/88LiL/PC4i/1tr//9ba///PC4i/zwuIv+SlTf/"
    "r7g/QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAK+4P0CSlTf/PC4i/zwuIv+vuD//r7g//zwuIv88LiL/WcX3/1nF9/88LiL/PC4i"
    "/1tr//9ba///PC4i/zwuIv+SlTf/r7g/QAAAAAAAAAAAAAAAAAAAAAAAAAAAxLCaQLuzc3CWlEj/PC4i/zwuIv88LiL/PC4i/zwu"
    "Iv88LiL/WcX3/1nF9/88LiL/PC4i/1tr//9ba///PC4i/zwuIv+WlEj/u7NzcMSwmkAAAAAAAAAAAAAAAAAAAAAAxLCa/8Swmv+i"
    "j3z/PC4i/zwuIv88LiL/PC4i/zwuIv88LiL/WcX3/1nF9/88LiL/PC4i/1tr//9ba///PC4i/zwuIv+ij3z/xLCa/8Swmv8AAAAA"
    "AAAAAAAAAAAAAAAAxLCa/8Swmv+ij3z/PC4i/zwuIv88LiL/PC4i/zwuIv88LiL/WcX3/1nF9/88LiL/PC4i/1tr//9ba///PC4i"
    "/zwuIv+ij3z/xLCa/8Swmv8AAAAAAAAAAAAAAAAAAAAAAAAAAK+4PxCvuD//UUcn/zwuIv88LiL/PC4i/zwuIv88LiL/UZ/B/1Gf"
    "wf88LiL/PC4i/1tr//9ba///PC4i/1FHJ/+vuD//r7g/EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACvuD9gr7g//6KPfP+i"
    "j3z/lpRI/5KVN/+SlTf/oo98/6KPfP+SlTf/kpU3/52jgP+pnrP/oo98/6+4P/+vuD9gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAr7g/EMSwmv/EsJr/u7NzcK+4P0CvuD9AxLCa/8Swmv+vuD9Ar7g/QLuzc3DEsJr/xLCa/6+4PxAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMSwmv/EsJr/xLCaQAAAAAAAAAAAxLCa/8Swmv8AAAAAAAAAAMSw"
    "mkDEsJr/xLCa/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAACgAAAAgAAAAQAAAAAEAIAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADEsJpgxLCagMSwmoAAAAAAAAAAAAAAAADE"
    "sJpAxLCagMSwmoDEsJpAAAAAAAAAAAAAAAAAxLCagMSwmoDEsJpgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMSwmr/EsJr/xLCa/wAAAAAAAAAAAAAAAMSwmoDEsJr/xLCa/8SwmoAAAAAAAAAA"
    "AAAAAADEsJr/xLCa/8Swmr8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAxLCav8Swmv/EsJr/AAAAAAAAAAAAAAAAxLCagMSwmv/EsJr/xLCagAAAAAAAAAAAAAAAAMSwmv/EsJr/xLCavwAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAr7g/UK+4P7+/sYfvxLCa/8Swmv+vuD//"
    "r7g//6+4P/+5tGz/xLCa/8Swmv+5tGz/r7g//6+4P/+vuD//xLCa/8Swmv+/sYfvr7g/v6+4P1AAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAK+4P1CvuD//kpU3/31wUv+Ab17/gG9e/3VzMP91czD/dXMw/3pxR/+Ab17/gG9e/3px"
    "R/91czD/dXMw/3VzMP+Ab17/gG9e/31wUv+SlTf/r7g//6+4P1AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAr7g/v5KVN/88LiL/PC4i/zwuIv88LiL/PC4i/zwuIv88LiL/PC4i/zwuIv88LiL/PC4i/zwuIv88LiL/PC4i/zwuIv88LiL/"
    "PC4i/zwuIv+SlTf/r7g/vwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADEsJpgxLCav8Swmr+/sYfvfXBS/zwuIv88LiL/PC4i"
    "/zwuIv88LiL/PC4i/zwuIv88LiL/PC4i/zwuIv88LiL/PC4i/zwuIv88LiL/PC4i/zwuIv88LiL/PC4i/31wUv+/sYfvxLCav8Sw"
    "mr/EsJpgAAAAAAAAAAAAAAAAAAAAAMSwmoDEsJr/xLCa/8Swmv+Ab17/PC4i/zwuIv+SlTf/r7g//6+4P/9YUCn/PC4i/0p5jP9Z"
    "xff/WcX3/0p5jP88LiL/Qz1Z/1tr//9ba///U1vH/zwuIv88LiL/gG9e/8Swmv/EsJr/xLCa/8SwmoAAAAAAAAAAAAAAAAAAAAAA"
    "xLCagMSwmv/EsJr/xLCa/4BvXv88LiL/PC4i/5KVN/+vuD//r7g//1hQKf88LiL/SnmM/1nF9/9Zxff/SnmM/zwuIv9DPVn/W2v/"
    "/1tr//9TW8f/PC4i/zwuIv+Ab17/xLCa/8Swmv/EsJr/xLCagAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACvuD//dXMw/zwu"
    "Iv88LiL/kpU3/6+4P/+vuD//WFAp/zwuIv9KeYz/WcX3/1nF9/9KeYz/PC4i/0M9Wf9ba///W2v//1Nbx/88LiL/PC4i/3VzMP+v"
    "uD//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAK+4P/91czD/PC4i/zwuIv+SlTf/r7g//6+4P/9YUCn/"
    "PC4i/0p5jP9Zxff/WcX3/0p5jP88LiL/Qz1Z/1tr//9ba///U1vH/zwuIv88LiL/dXMw/6+4P/8AAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAr7g//3VzMP88LiL/PC4i/5KVN/+vuD//r7g//1hQKf88LiL/SnmM/1nF9/9Zxff/SnmM/zwu"
    "Iv9DPVn/W2v//1tr//9TW8f/PC4i/zwuIv91czD/r7g//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADEsJpAxLCagMSwmoC5"
    "tGz/enFH/zwuIv88LiL/kpU3/6+4P/+vuD//WFAp/zwuIv9KeYz/WcX3/1nF9/9KeYz/PC4i/0M9Wf9ba///W2v//1Nbx/88LiL/"
    "PC4i/3pxR/+5tGz/xLCagMSwmoDEsJpAAAAAAAAAAAAAAAAAAAAAAMSwmoDEsJr/xLCa/8Swmv+Ab17/PC4i/zwuIv+SlTf/r7g/"
    "/6+4P/9YUCn/PC4i/0p5jP9Zxff/WcX3/0p5jP88LiL/Qz1Z/1tr//9ba///U1vH/zwuIv88LiL/gG9e/8Swmv/EsJr/xLCa/8Sw"
    "moAAAAAAAAAAAAAAAAAAAAAAxLCagMSwmv/EsJr/xLCa/4BvXv88LiL/PC4i/5KVN/+vuD//r7g//1hQKf88LiL/SnmM/1nF9/9Z"
    "xff/SnmM/zwuIv9DPVn/W2v//1tr//9TW8f/PC4i/zwuIv+Ab17/xLCa/8Swmv/EsJr/xLCagAAAAAAAAAAAAAAAAAAAAADEsJpA"
    "xLCagMSwmoC5tGz/enFH/zwuIv88LiL/kpU3/6+4P/+vuD//WFAp/zwuIv9KeYz/WcX3/1nF9/9KeYz/PC4i/0M9Wf9ba///W2v/"
    "/1Nbx/88LiL/PC4i/3pxR/+5tGz/xLCagMSwmoDEsJpAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAK+4P/91czD/PC4i/zwu"
    "Iv+SlTf/r7g//6+4P/9YUCn/PC4i/0p5jP9Zxff/WcX3/0p5jP88LiL/Qz1Z/1tr//9ba///U1vH/zwuIv88LiL/dXMw/6+4P/8A"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAr7g//3VzMP88LiL/PC4i/3x7Mv+SlTf/kpU3/1FHJ/88LiL/"
    "SnmM/1nF9/9Zxff/SnmM/zwuIv9DPVn/W2v//1tr//9TW8f/PC4i/zwuIv91czD/r7g//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAACvuD//dXMw/zwuIv88LiL/PC4i/zwuIv88LiL/PC4i/zwuIv9KeYz/WcX3/1nF9/9KeYz/PC4i/0M9"
    "Wf9ba///W2v//1Nbx/88LiL/PC4i/3VzMP+vuD//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMSwmoDEsJr/xLCa/8Swmv+A"
    "b17/PC4i/zwuIv88LiL/PC4i/zwuIv88LiL/PC4i/0p5jP9Zxff/WcX3/0p5jP88LiL/Qz1Z/1tr//9ba///U1vH/zwuIv88LiL/"
    "gG9e/8Swmv/EsJr/xLCa/8SwmoAAAAAAAAAAAAAAAAAAAAAAxLCagMSwmv/EsJr/xLCa/4BvXv88LiL/PC4i/zwuIv88LiL/PC4i"
    "/zwuIv88LiL/SnmM/1nF9/9Zxff/SnmM/zwuIv9DPVn/W2v//1tr//9TW8f/PC4i/zwuIv+Ab17/xLCa/8Swmv/EsJr/xLCagAAA"
    "AAAAAAAAAAAAAAAAAADEsJpgxLCav8Swmr+/sYfvfXBS/zwuIv88LiL/PC4i/zwuIv88LiL/PC4i/zwuIv9KeYz/WcX3/1nF9/9K"
    "eYz/PC4i/0M9Wf9ba///W2v//1Nbx/88LiL/PC4i/31wUv+/sYfvxLCav8Swmr/EsJpgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAK+4P7+SlTf/PC4i/zwuIv88LiL/PC4i/zwuIv88LiL/PC4i/0p5jP9Zxff/WcX3/0p5jP88LiL/Qz1Z/1tr//9ba///U1vH"
    "/zwuIv88LiL/kpU3/6+4P78AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAr7g/UK+4P/+SlTf/fXBS/4Bv"
    "Xv+Ab17/dXMw/3VzMP91czD/enFH/4BvXv+Ab17/enFH/3VzMP95ekz/hZGf/4+NzP+LhbD/fXBS/5KVN/+vuD//r7g/UAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAr7g/UK+4P7+/sYfvxLCa/8Swmv+vuD//r7g//6+4P/+5tGz/"
    "xLCa/8Swmv+5tGz/r7g//6+4P/+vuD//xLCa/8Swmv+/sYfvr7g/v6+4P1AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMSwmr/EsJr/xLCa/wAAAAAAAAAAAAAAAMSwmoDEsJr/xLCa/8SwmoAAAAAAAAAAAAAA"
    "AADEsJr/xLCa/8Swmr8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAxLCav8Swmv/EsJr/AAAAAAAAAAAAAAAAxLCagMSwmv/EsJr/xLCagAAAAAAAAAAAAAAAAMSwmv/EsJr/xLCavwAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADEsJpgxLCagMSwmoAAAAAAAAAA"
    "AAAAAADEsJpAxLCagMSwmoDEsJpAAAAAAAAAAAAAAAAAxLCagMSwmoDEsJpgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAA=";
    return kIcon;
}

inline std::vector<unsigned char> decode_base64(const char* s) {
    static signed char rev[256];
    static const bool init = [] {
        for (int i = 0; i < 256; ++i) rev[i] = -1;
        const char* abc = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
        for (int i = 0; i < 64; ++i) rev[(unsigned char)abc[i]] = (signed char)i;
        return true;
    }();
    (void)init;

    std::vector<unsigned char> out;
    int acc = 0, bits = 0;
    for (const char* p = s; *p; ++p) {
        const signed char v = rev[(unsigned char)*p];
        if (v < 0) continue;  // padding and whitespace
        acc = (acc << 6) | v;
        bits += 6;
        if (bits >= 8) {
            bits -= 8;
            out.push_back((unsigned char)((acc >> bits) & 0xFF));
        }
    }
    return out;
}

// Picks the image closest to cx from the .ico directory and turns it into an HICON.
// The caller owns the handle and destroys it with DestroyIcon.
inline HICON load_icon(int cx, int cy) {
    static const std::vector<unsigned char> ico = decode_base64(icon_base64());
    if (ico.size() < 6) return nullptr;
    const int count = ico[4] | (ico[5] << 8);
    if (count <= 0 || ico.size() < (size_t)(6 + 16 * count)) return nullptr;

    int best = -1, best_diff = 1 << 30;
    for (int i = 0; i < count; ++i) {
        const unsigned char* e = &ico[6 + 16 * i];
        const int w = e[0] ? e[0] : 256;
        const int diff = w >= cx ? (w - cx) : (cx - w) * 2;  // prefer scaling down
        if (diff < best_diff) {
            best_diff = diff;
            best = i;
        }
    }
    const unsigned char* e = &ico[6 + 16 * best];
    const unsigned int size = e[8] | (e[9] << 8) | (e[10] << 16) | ((unsigned)e[11] << 24);
    const unsigned int off = e[12] | (e[13] << 8) | (e[14] << 16) | ((unsigned)e[15] << 24);
    if ((size_t)off + size > ico.size()) return nullptr;
    return CreateIconFromResourceEx((PBYTE)(ico.data() + off), size, TRUE, 0x00030000, cx, cy, LR_DEFAULTCOLOR);
}

}  // namespace cpulytics
