#include <windows.h>
#include <shellapi.h>

#include <filesystem>
#include <fstream>
#include <memory>
#include <string>
#include <vector>

#include "config.h"
#include "engine.h"
#include "i18n.h"
#include "settings.h"
#include "sysinfo.h"
#include "theme.h"
#include "util.h"

// version.h is generated by scripts/build.ps1 from the current git tag.
#if defined(__has_include)
#if __has_include("version.h")
#include "version.h"
#endif
#endif
#ifndef CPULYTICS_VERSION
#define CPULYTICS_VERSION "dev"
#endif
#define CPULYTICS_VERSION_W L"" CPULYTICS_VERSION

namespace cpulytics {
namespace {

constexpr UINT WM_TRAY = WM_APP + 1;
constexpr UINT kTimerId = 1;
constexpr UINT kIdExit = 100;
constexpr UINT kIdEnabled = 101;
constexpr UINT kIdRestoreAll = 102;
constexpr UINT kIdSettings = 103;
constexpr UINT kIdReload = 104;
constexpr UINT kIdLog = 105;
constexpr UINT kIdElevate = 106;
constexpr size_t kTopRows = 6;
constexpr wchar_t kWindowClass[] = L"cpulytics_hidden";

// A second launch pings the running instance instead of opening a dialog nobody
// asked for. Message only windows are invisible to HWND_BROADCAST, so the ping
// is posted to the window found by class.
UINT already_running_message() {
    static const UINT m = RegisterWindowMessageW(L"cpulytics-already-running");
    return m;
}

HWND find_running_instance() { return FindWindowExW(HWND_MESSAGE, nullptr, kWindowClass, nullptr); }

// Held for the lifetime of the process, released before handing over to an
// elevated copy of ourselves.
HANDLE g_singleton = nullptr;
constexpr wchar_t kSingletonName[] = L"Local\\cpulytics-singleton";

std::wstring config_dir() {
    const std::wstring p = Config::path();
    const size_t slash = p.find_last_of(L'\\');
    return slash == std::wstring::npos ? L"." : p.substr(0, slash);
}

std::wstring log_path() { return config_dir() + L"\\cpulytics.log"; }

// What is held demoted right now, so that a crash or a kill does not leave
// processes stuck at a lowered priority until the next reboot.
std::wstring state_path() { return config_dir() + L"\\state.txt"; }

// Append only log with a hard size cap: it can never fill the disk of a machine
// that runs the app for months.
class Log {
public:
    void configure(bool on, int max_kb) {
        on_ = on;
        max_bytes_ = (uint64_t)max_kb * 1024;
        if (!on_) out_.close();
    }

    void write(const std::wstring& line) {
        if (!on_) return;
        const std::filesystem::path p(log_path());
        std::error_code ec;
        if (!out_.is_open()) {
            const auto sz = std::filesystem::file_size(p, ec);
            out_.open(p, (!ec && sz > max_bytes_) ? std::ios::trunc : std::ios::app);
            if (!out_) return;
        }
        SYSTEMTIME t;
        GetLocalTime(&t);
        char stamp[32];
        wsprintfA(stamp, "%04u-%02u-%02u %02u:%02u:%02u ", t.wYear, t.wMonth, t.wDay, t.wHour, t.wMinute, t.wSecond);
        out_ << stamp << narrow(line) << "\n";
        out_.flush();
        written_ += line.size() + 24;
        if (written_ > max_bytes_) {  // rotate by truncation, one file, no leftovers
            out_.close();
            written_ = 0;
            out_.open(p, std::ios::trunc);
        }
    }

private:
    bool on_ = true;
    uint64_t max_bytes_ = 512 * 1024;
    uint64_t written_ = 0;
    std::ofstream out_;
};

class App {
public:
    bool init(HINSTANCE inst);
    void shutdown();
    LRESULT wnd_proc(HWND hwnd, UINT msg, WPARAM wp, LPARAM lp);

private:
    void tick();
    void apply(const Action& a, std::wstring& summary, int& count);
    void show_menu();
    void notify(const std::wstring& title, const std::wstring& text);
    void set_tip();
    void add_icon();
    void reload_config();
    void save_state();
    void recover_state();
    void open_settings();
    void restart_elevated();
    void restore_all();

    HINSTANCE inst_ = nullptr;
    HWND hwnd_ = nullptr;
    NOTIFYICONDATAW nid_{};
    HICON icon_ = nullptr;
    UINT taskbar_created_ = 0;
    Config cfg_;
    std::unique_ptr<Engine> engine_;
    sys::Sampler sampler_;
    std::vector<ProcInfo> procs_;
    Log log_;
};

App* g_app = nullptr;

LRESULT CALLBACK wnd_proc_thunk(HWND hwnd, UINT msg, WPARAM wp, LPARAM lp) {
    return g_app ? g_app->wnd_proc(hwnd, msg, wp, lp) : DefWindowProcW(hwnd, msg, wp, lp);
}

void App::add_icon() {
    nid_ = {};
    nid_.cbSize = sizeof(nid_);
    nid_.hWnd = hwnd_;
    nid_.uID = 1;
    nid_.uFlags = NIF_ICON | NIF_MESSAGE | NIF_TIP;
    nid_.uCallbackMessage = WM_TRAY;
    nid_.hIcon = icon_;
    lstrcpynW(nid_.szTip, L"cpulytics", ARRAYSIZE(nid_.szTip));
    Shell_NotifyIconW(NIM_ADD, &nid_);
}

bool App::init(HINSTANCE inst) {
    inst_ = inst;
    theme::init_process();  // dark popup menus and dark controls when windows is dark
    cfg_ = Config::load();
    set_language(cfg_.language);
    // The setting is the truth: this repairs the entry after the exe was moved,
    // and clears it if the file was edited by hand.
    sys::set_autostart(cfg_.autostart);
    log_.configure(cfg_.log_enabled, cfg_.log_max_kb);
    engine_ = std::make_unique<Engine>(cfg_);

    WNDCLASSEXW wc{};
    wc.cbSize = sizeof(wc);
    wc.lpfnWndProc = wnd_proc_thunk;
    wc.hInstance = inst;
    wc.lpszClassName = kWindowClass;
    if (!RegisterClassExW(&wc)) return false;

    hwnd_ = CreateWindowExW(0, wc.lpszClassName, L"cpulytics", 0, 0, 0, 0, 0, HWND_MESSAGE, nullptr, inst, nullptr);
    if (!hwnd_) return false;

    // Resource 1 is the icon of the executable, so the tray and explorer show
    // exactly the same image, in the size each of them asks for.
    icon_ = (HICON)LoadImageW(inst, MAKEINTRESOURCEW(1), IMAGE_ICON, GetSystemMetrics(SM_CXSMICON),
                              GetSystemMetrics(SM_CYSMICON), LR_DEFAULTCOLOR);
    taskbar_created_ = RegisterWindowMessageW(L"TaskbarCreated");
    add_icon();
    recover_state();
    SetTimer(hwnd_, kTimerId, (UINT)cfg_.sample_interval_ms, nullptr);
    log_.write(L"started, version " + widen(CPULYTICS_VERSION));
    return true;
}

void App::shutdown() {
    KillTimer(hwnd_, kTimerId);
    if (cfg_.restore_on_exit) restore_all();
    Shell_NotifyIconW(NIM_DELETE, &nid_);
    if (icon_) DestroyIcon(icon_);
    icon_ = nullptr;
    log_.write(L"stopped");
}

void App::restore_all() {
    int n = 0;
    for (const Held& h : engine_->modified())
        if (sys::apply_step(h.pid, h.orig_class, 0)) ++n;  // also clears EcoQoS
    engine_->forget_all();
    save_state();
    if (n) log_.write(L"restored " + std::to_wstring(n) + L" process(es)");
}

// One line per held process: pid, create time, and the class it had before.
void App::save_state() {
    const std::filesystem::path p(state_path());
    const auto held = engine_->modified();
    std::error_code ec;
    if (held.empty()) {
        std::filesystem::remove(p, ec);
        return;
    }
    std::ofstream out(p, std::ios::trunc);
    if (!out) return;
    for (const Held& h : held) out << h.pid << " " << h.create_time << " " << h.orig_class << "\n";
}

// Runs once at startup: whatever the previous instance was still holding when it
// was killed is put back, as long as the pid belongs to the same process.
void App::recover_state() {
    const std::filesystem::path p(state_path());
    std::ifstream in(p);
    if (!in) return;

    std::vector<Held> held;
    uint32_t pid = 0, orig = 0;
    uint64_t created = 0;
    while (in >> pid >> created >> orig) held.push_back({pid, created, orig, 1});
    in.close();
    std::error_code ec;
    std::filesystem::remove(p, ec);
    if (held.empty()) return;

    std::vector<ProcInfo> procs;
    if (!sampler_.sample(procs)) return;
    int n = 0;
    for (const Held& h : held) {
        for (const ProcInfo& proc : procs) {
            // Same pid and same start time: it really is the process we demoted.
            if (proc.pid == h.pid && proc.create_time == h.create_time) {
                if (sys::apply_step(h.pid, h.orig_class, 0)) ++n;
                break;
            }
        }
    }
    if (n) log_.write(L"restored " + std::to_wstring(n) + L" process(es) held by the previous run");
}

void App::reload_config() {
    cfg_ = Config::load();
    set_language(cfg_.language);
    sys::set_autostart(cfg_.autostart);
    log_.configure(cfg_.log_enabled, cfg_.log_max_kb);
    engine_->set_config(cfg_);
    KillTimer(hwnd_, kTimerId);
    SetTimer(hwnd_, kTimerId, (UINT)cfg_.sample_interval_ms, nullptr);
    if (!cfg_.enabled) restore_all();
    log_.write(L"settings reloaded");
    set_tip();
}

// Settings live in their own window; the sampling timer keeps running behind it.
void App::open_settings() {
    if (!show_settings(inst_, cfg_)) return;
    engine_->set_config(cfg_);
    if (!sys::set_autostart(cfg_.autostart)) log_.write(L"could not change the autostart entry");
    log_.configure(cfg_.log_enabled, cfg_.log_max_kb);
    KillTimer(hwnd_, kTimerId);
    SetTimer(hwnd_, kTimerId, (UINT)cfg_.sample_interval_ms, nullptr);
    if (!cfg_.enabled) restore_all();
    log_.write(L"settings saved");
    set_tip();
}

// Processes of other users, services and elevated programs cannot be touched
// without elevation. Restarting through the shell is the only way to ask for it.
void App::restart_elevated() {
    wchar_t exe[MAX_PATH];
    if (!GetModuleFileNameW(nullptr, exe, MAX_PATH)) return;
    if (cfg_.restore_on_exit) restore_all();

    // The elevated copy starts while we are still alive: hand the singleton over
    // first, otherwise it would find us and quit again.
    if (g_singleton) {
        ReleaseMutex(g_singleton);
        CloseHandle(g_singleton);
        g_singleton = nullptr;
    }
    SHELLEXECUTEINFOW si{};
    si.cbSize = sizeof(si);
    si.lpVerb = L"runas";
    si.lpFile = exe;
    si.nShow = SW_SHOW;
    if (ShellExecuteExW(&si)) {
        if (si.hProcess) CloseHandle(si.hProcess);
        DestroyWindow(hwnd_);  // the elevated copy takes over
    } else {
        g_singleton = CreateMutexW(nullptr, TRUE, kSingletonName);  // declined, stay
        log_.write(L"elevation declined");
    }
}

void App::apply(const Action& a, std::wstring& summary, int& count) {
    const bool demote = a.kind == ActionKind::Demote;
    // The class the process had before we ever touched it is the only safe base:
    // reading the current one would ratchet the process down step after step.
    const uint32_t orig = a.from_step > 0 ? engine_->orig_class(a.pid) : sys::priority_class(a.pid);
    if (!orig || !sys::apply_step(a.pid, orig, a.to_step, cfg_.eco_qos)) {
        const DWORD err = GetLastError();
        engine_->failed(a.pid);  // out of reach, stop trying until it restarts
        if (err == ERROR_ACCESS_DENIED)
            log_.write(a.name + L" (pid " + std::to_wstring(a.pid) + L"): access denied, needs elevation");
        return;
    }
    engine_->applied(a.pid, a.to_step, orig);

    wchar_t line[256];
    wsprintfW(line, L"%s: %s (pid %u) %s -> %s at %u%% avg", demote ? L"demote" : L"restore", a.name.c_str(), a.pid,
              sys::class_name(sys::class_for_step(orig, a.from_step)), sys::class_name(sys::class_for_step(orig, a.to_step)),
              (unsigned)(a.percent + 0.5));
    log_.write(line);
    if (++count <= 3) {
        summary += a.name;
        summary += demote ? L" -> " : L" back to ";
        summary += sys::class_name(sys::class_for_step(orig, a.to_step));
        summary += L"\n";
    }
}

void App::tick() {
    if (!sampler_.sample(procs_)) return;
    const auto actions = engine_->update(now_ms(), procs_, sys::foreground_pid(), sys::fullscreen_pid());

    std::wstring summary;
    int count = 0, demotions = 0;
    for (const Action& a : actions) {
        if (a.kind == ActionKind::Demote) ++demotions;
        apply(a, summary, count);
    }
    set_tip();
    if (!count) return;
    save_state();
    if (cfg_.notifications) {
        if (count > 3) {
            wchar_t more[64];
            wsprintfW(more, tr(S_BALLOON_MORE), (unsigned)(count - 3));
            summary += std::wstring(more) + L"\n";
        }
        notify(tr(demotions ? S_BALLOON_LOWERED : S_BALLOON_RESTORED), summary);
    }
}

void App::set_tip() {
    const auto top = engine_->top(1);
    std::wstring tip = L"cpulytics";
    if (!cfg_.enabled) tip += std::wstring(L" (") + tr(S_PAUSED) + L")";
    if (!top.empty()) {
        wchar_t buf[96];
        wsprintfW(buf, L"\n%s: %s %u%%", tr(S_TOP), top[0].name.c_str(), (unsigned)(top[0].percent + 0.5));
        tip += buf;
    }
    nid_.uFlags = NIF_TIP;
    lstrcpynW(nid_.szTip, tip.c_str(), ARRAYSIZE(nid_.szTip));
    Shell_NotifyIconW(NIM_MODIFY, &nid_);
}

void App::notify(const std::wstring& title, const std::wstring& text) {
    nid_.uFlags = NIF_INFO;
    nid_.dwInfoFlags = NIIF_INFO | NIIF_NOSOUND;
    lstrcpynW(nid_.szInfoTitle, title.c_str(), ARRAYSIZE(nid_.szInfoTitle));
    lstrcpynW(nid_.szInfo, text.c_str(), ARRAYSIZE(nid_.szInfo));
    Shell_NotifyIconW(NIM_MODIFY, &nid_);
}

void App::show_menu() {
    HMENU menu = CreatePopupMenu();
    if (!menu) return;

    std::wstring header = L"cpulytics " CPULYTICS_VERSION_W;
    if (sys::is_elevated()) header += std::wstring(L" (") + tr(S_ADMINISTRATOR) + L")";
    AppendMenuW(menu, MF_STRING | MF_GRAYED, 0, header.c_str());
    AppendMenuW(menu, MF_SEPARATOR, 0, nullptr);
    for (const Usage& u : engine_->top(kTopRows)) {
        wchar_t row[160];
        const wchar_t* tag = u.step ? (u.step > 1 ? tr(S_TAG_IDLE) : tr(S_TAG_LOWERED))
                                    : (engine_->is_fullscreen(u.pid) ? tr(S_TAG_FULLSCREEN) : nullptr);
        wsprintfW(row, tag ? L"%s  %u%%  [%s]" : L"%s  %u%%", u.name.c_str(), (unsigned)(u.percent + 0.5), tag);
        AppendMenuW(menu, MF_STRING | MF_GRAYED, 0, row);
    }
    AppendMenuW(menu, MF_SEPARATOR, 0, nullptr);
    AppendMenuW(menu, MF_STRING | (cfg_.enabled ? MF_CHECKED : 0), kIdEnabled, tr(S_MENU_MANAGING));
    AppendMenuW(menu, MF_STRING, kIdRestoreAll, tr(S_MENU_RESTORE_ALL));
    AppendMenuW(menu, MF_SEPARATOR, 0, nullptr);
    AppendMenuW(menu, MF_STRING, kIdSettings, tr(S_MENU_SETTINGS));
    AppendMenuW(menu, MF_STRING, kIdReload, tr(S_MENU_RELOAD));
    if (!sys::is_elevated()) AppendMenuW(menu, MF_STRING, kIdElevate, tr(S_MENU_ELEVATE));
    AppendMenuW(menu, MF_STRING, kIdLog, tr(S_MENU_LOG));
    AppendMenuW(menu, MF_SEPARATOR, 0, nullptr);
    AppendMenuW(menu, MF_STRING, kIdExit, tr(S_MENU_EXIT));

    POINT pt;
    GetCursorPos(&pt);
    SetForegroundWindow(hwnd_);  // otherwise the menu never closes on click-away
    TrackPopupMenu(menu, TPM_RIGHTBUTTON, pt.x, pt.y, 0, hwnd_, nullptr);
    PostMessageW(hwnd_, WM_NULL, 0, 0);
    DestroyMenu(menu);
}

LRESULT App::wnd_proc(HWND hwnd, UINT msg, WPARAM wp, LPARAM lp) {
    switch (msg) {
        case WM_TIMER:
            if (wp == kTimerId) tick();
            return 0;

        case WM_TRAY:
            if (LOWORD(lp) == WM_RBUTTONUP || LOWORD(lp) == WM_LBUTTONUP) show_menu();
            return 0;

        case WM_COMMAND:
            switch (LOWORD(wp)) {
                case kIdEnabled:
                    cfg_.enabled = !cfg_.enabled;
                    engine_->set_config(cfg_);
                    if (!cfg_.enabled) restore_all();
                    cfg_.save();
                    set_tip();
                    break;
                case kIdRestoreAll: restore_all(); break;
                case kIdSettings: open_settings(); break;
                case kIdElevate: restart_elevated(); break;
                case kIdReload: reload_config(); break;
                case kIdLog: ShellExecuteW(nullptr, L"open", log_path().c_str(), nullptr, nullptr, SW_SHOW); break;
                case kIdExit: DestroyWindow(hwnd); break;
            }
            return 0;

        // Light and dark switched: the menu is rebuilt on every click anyway, it
        // only needs the theme cache flushed.
        case WM_SETTINGCHANGE:
            if (lp && lstrcmpiW((const wchar_t*)lp, L"ImmersiveColorSet") == 0) theme::init_process();
            return DefWindowProcW(hwnd, msg, wp, lp);

        case WM_QUERYENDSESSION:
            if (cfg_.restore_on_exit) restore_all();
            return TRUE;

        case WM_DESTROY:
            shutdown();
            PostQuitMessage(0);
            return 0;

        default:
            if (msg == taskbar_created_ && taskbar_created_) add_icon();  // explorer restarted
            if (msg == already_running_message()) {
                notify(L"cpulytics", tr(S_ALREADY_RUNNING));
                set_tip();
            }
            return DefWindowProcW(hwnd, msg, wp, lp);
    }
}

}  // namespace
}  // namespace cpulytics

int WINAPI wWinMain(HINSTANCE inst, HINSTANCE, LPWSTR, int) {
    using namespace cpulytics;

    // One instance only: two of them would fight over the same priorities, and
    // each would undo what the other just did.
    g_singleton = CreateMutexW(nullptr, TRUE, kSingletonName);
    if (!g_singleton || GetLastError() == ERROR_ALREADY_EXISTS) {
        if (HWND running = find_running_instance()) PostMessageW(running, already_running_message(), 0, 0);
        if (g_singleton) CloseHandle(g_singleton);
        return 0;
    }

    App app;
    g_app = &app;
    int rc = 1;
    if (app.init(inst)) {
        MSG msg;
        while (GetMessageW(&msg, nullptr, 0, 0) > 0) {
            TranslateMessage(&msg);
            DispatchMessageW(&msg);
        }
        rc = (int)msg.wParam;
    }
    g_app = nullptr;
    if (g_singleton) {
        ReleaseMutex(g_singleton);
        CloseHandle(g_singleton);
    }
    return rc;
}
